// Generates bounds.js from the shapes in index.js. Run after editing a shape:
// `npm run bounds`. Paths only use M/L/H/V/Z, so tracking points is enough.
import { writeFileSync } from "node:fs";
import countries from "../index.js";

const round = (n) => Math.round(n * 10) / 10;

function subpaths(path) {
	const polygons = [];
	let points = null;
	let [x, y, startX, startY] = [0, 0, 0, 0];
	for (const [, command, args] of path.matchAll(/([a-zA-Z])([^a-zA-Z]*)/g)) {
		const n = (args.match(/-?\d*\.?\d+(?:e-?\d+)?/g) ?? []).map(Number);
		const relative = command === command.toLowerCase();
		switch (command.toLowerCase()) {
			case "m":
			case "l":
				for (let i = 0; i + 1 < n.length; i += 2) {
					x = relative ? x + n[i] : n[i];
					y = relative ? y + n[i + 1] : n[i + 1];
					if (command.toLowerCase() === "m" && i === 0) {
						[startX, startY] = [x, y];
						points = [];
						polygons.push(points);
					}
					points.push([x, y]);
				}
				break;
			case "h":
				for (const v of n) {
					x = relative ? x + v : v;
					points.push([x, y]);
				}
				break;
			case "v":
				for (const v of n) {
					y = relative ? y + v : v;
					points.push([x, y]);
				}
				break;
			case "z":
				[x, y] = [startX, startY];
				break;
			default:
				throw new Error(`Unexpected path command ${command}`);
		}
	}
	return polygons;
}

const box = (points) => [
	Math.min(...points.map(([x]) => x)),
	Math.min(...points.map(([, y]) => y)),
	Math.max(...points.map(([x]) => x)),
	Math.max(...points.map(([, y]) => y)),
];

// Shoelace formula. Comparing bounding boxes instead picks long, thin islands
// over compact larger ones (Sumatra over Borneo for Indonesia).
const area = (points) =>
	Math.abs(
		points.reduce((sum, [x1, y1], i) => {
			const [x2, y2] = points[(i + 1) % points.length];
			return sum + x1 * y2 - x2 * y1;
		}, 0),
	) / 2;

const lines = countries.map(({ id, shape }) => {
	const polygons = subpaths(shape);
	const bounds = box(polygons.flat()).map(round);
	const mainland = box(
		polygons.reduce((a, b) => (area(b) > area(a) ? b : a)),
	).map(round);
	return `  ${id}: { bounds: [${bounds.join(", ")}], mainland: [${mainland.join(", ")}] }`;
});

writeFileSync(
	new URL("../bounds.js", import.meta.url),
	`// Generated by scripts/bounds.js from index.js. Do not edit by hand.\nexport default {\n${lines.join(",\n")}\n};\n`,
);
console.log(`Bounds for ${lines.length} countries`);
