// Generates world-map.svg from the shapes in index.js: `npm run generate`.
import { writeFileSync } from "node:fs";
import countries, { HEIGHT, VIEW_BOX, WIDTH } from "../index.js";

const names = new Intl.DisplayNames(["en"], { type: "region" });
const escape = (s) => s.replaceAll("&", "&amp;").replaceAll('"', "&quot;");

// Presentation attributes rather than inline styles, so any CSS rule overrides them.
// Mid grey with white borders reads on light and dark backgrounds alike.
const svg = `<?xml version="1.0" encoding="UTF-8"?>
<!--
Generated by scripts/svg.js from index.js. Do not edit by hand.

Shapes derived from the Simplemaps world map (https://simplemaps.com/resources/svg-world).
Copyright (c) 2015 Pareto Softare, LLC DBA Simplemaps.com. MIT License, see LICENSE.
-->
<svg xmlns="http://www.w3.org/2000/svg" width="${WIDTH}" height="${HEIGHT}" viewBox="${VIEW_BOX}">
<g fill="#a8a29e" stroke="#fff" stroke-width="0.5">
${countries
	.map(({ id, shape }) => `<path id="${id}" data-name="${escape(names.of(id))}" d="${shape}"/>`)
	.join("\n")}
</g>
</svg>
`;

writeFileSync(new URL("../world-map.svg", import.meta.url), svg);
console.log(`SVG with ${countries.length} countries`);
